// Generated by init function
package configs

import (
	"github.com/prometheus/client_golang/prometheus"
)

var (
	//Roter farm1
	//##########################################
	farm1Sim1 = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "sim1",
			Name:      "status_farm1",
			Help:      "farm1 SIM 1 status",
		})

	farm1Sim1Error = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "sim1",
			Name:      "errors_farm1",
			Help:      "farm1 Sim 1 errors",
		})

	farm1Sim2 = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "sim2",
			Name:      "status_farm1",
			Help:      "farm1 SIM 2 status",
		})

	farm1Sim2Error = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "sim2",
			Name:      "errors_farm1",
			Help:      "farm1 Sim 2 errors",
		})
)
